import type { Metadata } from "next";
import localFont from "next/font/local";
import GlobalStyles from "./globalStyled"; // Certifique-se de que o caminho está correto
import Cabecalho from "./Cabecalho";
import Rodape from "./components/Rodape";
import Menu from "./components/Menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalStyles />
        <Menu />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
